CREATE USER 'darcey'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'darcey'@'%';
FLUSH PRIVILEGES;


/*
CREATE DATABASE IF NOT EXISTS hapihomes;
CREATE USER IF NOT EXISTS 'darcey'@'%' IDENTIFIED WITH 'caching_sha2_password' BY '123456';
GRANT ALL PRIVILEGES ON hapihomes.* TO 'darcey'@'%';
FLUSH PRIVILEGES;



CREATE DATABASE IF NOT EXISTS hapihomes;
CREATE USER IF NOT EXISTS 'darcey'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON hapihomes.* TO 'darcey'@'%';
FLUSH PRIVILEGES;
*/