
CREATE DATABASE IF NOT EXISTS wp_db;


-- CREATE USER IF NOT EXISTS 'darcey'@'%' IDENTIFIED WITH 'caching_sha2_password' BY '123456';
-- GRANT ALL PRIVILEGES ON wp_db.* TO 'darcey'@'%';
-- FLUSH PRIVILEGES;



-- CREATE DATABASE IF NOT EXISTS wp_db;
-- CREATE USER IF NOT EXISTS 'darcey'@'%' IDENTIFIED BY '123456';
-- GRANT ALL PRIVILEGES ON wp_db.* TO 'darcey'@'%';
-- FLUSH PRIVILEGES;